export class Actions {
  id?: string;                // ID Mongo DB - (AUTOGENERATED)
  inventoryId?: string;       // Action Inventory ID (AUTOGENERATED)
  creationDate?: string;      // Action creation date - (AUTOGENERATED)
  creator?: string;           // Action creator name - (AUTOGENERATED)
  creatorId?: string;         // Action creator ID - (AUTOGENERATED)
  actions?: string;           // Action list
}