export class Inventory {
    id?: string;                // ID Mongo DB - (AUTOGENERATED)
    name?: string;              // Inventory name
    type?: string;              // Inventory type (xlsx, json)
    year?: string;              // Inventory creation year
    creationDate?: string;      // Inventory creation date - (AUTOGENERATED)
    creator?: string;           // Inventory creator name - (AUTOGENERATED)
    creatorId?: string;         // Inventory creator ID - (AUTOGENERATED)
    public?: boolean;        // Is inventory private?
    fileUrl?: string;           // Inventory file name
}
