export class Model {
  id?: string;                    // ID Mongo DB - (AUTOGENERATED)
  name?: string;                  // Model name
  description?: string;           // Model description
  type?: string;                  // Model Type
  docs?: string;                  // Model documentation file
  creatorId?: string;         // Inventory creator ID - (AUTOGENERATED)
  status?: string;                // Model status (stable / in development)
  modelPath?: string;             // Model supercomputer path (Scenario JSON)
  modelClass?: string;            // Model supercomputer class (Scenario JSON)
  operation?: string;             // Model operation (Scenario JSON)
  specie?: string;             // Specie of the trees (Scenario JSON)
  applicationArea?: string;    // Application area of the model
  executionPeriod?: string;    // Execution period of the model
  operatingDimensions?: string; // Operating dimensions of the model
}
