export class Scenario {
  id?: string;
  inventoryName?: string;
  inventoryId?: string;
  steps?: any;
  jsonFile?: string;
  creatorId?: string;         // Inventory creator ID - (AUTOGENERATED)
  creatorName?: string;
  status?: string;
  outputFile?: string;
  jobId?: string;
  modelClass?: string;
  modelPath?: string;
}
