FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY blockips.conf /etc/nginx/blockips.conf
COPY certificates/certificate.crt /etc/nginx/ssl/certificate.crt
COPY certificates/certificate.key /etc/nginx/ssl/certificate.key
COPY certificates/certificate.pem /etc/nginx/ssl/certificate.pem
