version: '3.4'

networks:
# docker network create simanfor --internal (SE AISLARIA PERO NO FUNCIONA)
# docker network create simanfor (USA MODO bridge POR DEFECTO)
  simanfor:
    external: true

services:

  proxy-inverse:
    container_name: proxy
    image: simanfor-dask/production:latest
    build: 
      context: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - simanfor
    depends_on:
      - web-frontend

  web-frontend:
    container_name: frontend
    image: simanfor-dask/web-frontend:latest
    build:
      context: ../web-frontend
    restart: always
    depends_on:
      - web-backend
    networks:
      - simanfor

  web-backend:
    container_name: backend
    image: simanfor-dask/web-backend:latest
    build:
      context: ../web-backend
    restart: always
    ports:
      - "3000:3000"
    #Check which port uses Node docker container
    environment:
      SSH_HOST: calendula.scayle.es
      SSH_PORT: 2222
      SSH_USERNAME: uva_iufor_1_3
      SSH_PASSWORD: QvJh"b'5>C_2
      SCRATCH_PATH: /scratch/uva_iufor_1/uva_iufor_1_3
      INPUT_SCRATCH_PATH: /input
      OUTPUT_SCRATCH_PATH: /output
      MONGO_HOST: mongodb://sngular_aia_1_3:P1l1nh004.@mongo
      MONGO_DB: simanfor
      JWT_MASTER_TOKEN: simanforsngular
      PRODUCTION: 1
    volumes:
      - /home/rafagc/simanfor-rgc/persist/data_input:/usr/src/app/input
      - /home/rafagc/simanfor-rgc/persist/data_output:/usr/src/app/output
    depends_on:
      - mongo
    networks:
      - simanfor

  mongo:
    container_name: mongo
    image: mongo:4.2.8-bionic
    restart: always
    ports:
      - 8081:8081
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sngular_aia_1_3
      MONGO_INITDB_ROOT_PASSWORD: P1l1nh004.
      MONGO_INITDB_DATABASE: simanfor
    volumes:
      - /home/rafagc/simanfor-rgc/persist/mongodb:/data/db
    networks:
      - simanfor

