version: '3.4'

networks:
  simanforv2:
    external: false

services:

  proxy-inverse:
    container_name: proxy
    image: simanfor-dask/production:latest
    build: 
      context: .
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - simanforv2
    depends_on:
      - web-frontend

  web-frontend:
    container_name: frontend
    image: simanfor-dask/web-frontend:latest
    build:
      context: ../web-frontend
    restart: always
    depends_on:
      - web-backend
    networks:
      - simanforv2

  web-backend:
    container_name: backend
    image: simanfor-dask/web-backend:latest
    build:
      context: ../web-backend
    restart: always
    ports:
      - 3000:3000
    #Check which port uses Node docker container
    environment:
      SSH_HOST: 157.88.224.203
      SSH_PORT: 22
      SSH_USERNAME: simanfor
      SSH_PASSWORD: 5%9a4C6&
      SCRATCH_PATH: /scratch/simanfor
      INPUT_SCRATCH_PATH: /input
      OUTPUT_SCRATCH_PATH: /output
      MONGO_HOST: mongodb://database_simanfor_test:simanforlocaltest@mongo:27017/
      MONGO_DB: simanfor_tiny
      JWT_MASTER_TOKEN: simanforsngular
      # PRODUCTION: 1
    volumes:
      - /home/rafagc/TFG_SimanforV2/persist-tfg/data_input/inventory:/usr/src/app/input/inventory
      - /home/rafagc/TFG_SimanforV2/persist-tfg/data_input/scenario:/usr/src/app/input/scenario
      - /home/rafagc/TFG_SimanforV2/persist-tfg/data_output:/usr/src/app/output
    depends_on:
      - mongo
    networks:
      - simanforv2

  mongo:
    container_name: mongo
    image: mongo:4.2.8-bionic
    restart: always
    ports:
      # - 8081:8081
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: database_simanfor_test
      MONGO_INITDB_ROOT_PASSWORD: simanforlocaltest
      MONGO_INITDB_DATABASE: simanfor_tiny
    volumes:
      - /home/rafagc/persist-tfg/mongodb:/data/db
    networks:
      - simanforv2

  rstudio:
    container_name: simforstudio
    image: rocker/verse:latest
    build: 
      context: ./rstudio
    restart: always
    ports:
      - 8787:8787
    environment:
      - PASSWORD=rmv2mil24.
      - ROOT=true
      - DISABLE_AUTH=true
    volumes:
      - /home/rafagc/TFG_SimanforV2/persist-tfg/rstudio:/home/rstudio
      - /home/rafagc/TFG_SimanforV2/persist-tfg/data_output:/home/rstudio/data
    networks:
      - simanforv2